[workspace]
resolver = "2"

members = [
    "ppu",
    "rusty-boy",
    "sm83",
    "sm83_decoder_macros",
    "cartridge",
    "timer", "rusty-boy-sdl", "rb-disasm",
]

exclude = [
    "rusty-date",
]

[profile.release]
debug = true
