[package]
name = "rusty-boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sm83 = { path =  "../sm83", version = "0.1.0" }
ppu = { path =  "../ppu", version = "0.1.0" }
anyhow = "1.0"
png = "0.17"
