[package]
name = "rusty-boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rb-disasm"

[dependencies]
sm83 = { path =  "../sm83", version = "0.1.0" }
ppu = { path =  "../ppu", version = "0.1.0" }
anyhow = "1.0"
png = "0.17"
sdl2 = "0.36"
clap = { version = "4.5.4", features = ["derive"] }
