name: Rusty Boy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly-2025-03-15
        components: rustfmt, clippy, rust-src
    - run: cargo clippy

  cargo_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly-2025-03-15
        components: rustfmt, clippy, rust-src
    - run: sudo apt-get install libsdl2-dev
    - run: cargo test

  cargo_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@v1
      with:
        targets: thumbv7em-none-eabihf
        toolchain: nightly-2025-03-15
        components: rustfmt, clippy, rust-src
    - run: sudo apt-get install libsdl2-dev
    - run: |
        wget https://download.panic.com/playdate_sdk/Linux/PlaydateSDK-2.4.2.tar.gz
        tar -xf PlaydateSDK-2.4.2.tar.gz
    - run: PLAYDATE_SDK_PATH=${{ github.workspace }}/PlaydateSDK-2.4.2 cargo xtask build --release
    - name: Archive rusty-date
      uses: actions/upload-artifact@v4
      with:
        name: rusty-date
        path: rusty-date/build/rusty_date.pdx

  cargo_fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly-2025-03-15
        components: rustfmt, clippy, rust-src
    - run: cargo fmt --check

  cargo_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly-2025-03-15
        components: rustfmt, clippy, rust-src
    - run: cargo doc

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v2.0.10
